//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public string MAND { get; set; }
        public string PASSWORD { get; set; }
        public string TENNV { get; set; }
        public string EMAIL { get; set; }
        public string DIACHI { get; set; }
        public short MAQUYEN { get; set; }
    
        public virtual QUYEN QUYEN { get; set; }
    }
}
