//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCafe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDATHANGs = new HashSet<CHITIETDATHANG>();
            this.CHITIETNHAPHANGs = new HashSet<CHITIETNHAPHANG>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public int MALH { get; set; }
        public int HANGTON { get; set; }
        public int MANCC { get; set; }
        public int MaDVT { get; set; }
        public string HinhAnh { get; set; }
        public long GIA { get; set; }
        public bool TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATHANG> CHITIETDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETNHAPHANG> CHITIETNHAPHANGs { get; set; }
        public virtual DONVITINH DONVITINH { get; set; }
        public virtual LOAIHANG LOAIHANG { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
